/*
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

// FeatureSettingsUpdateSpec Information related to Feature Settings.
type FeatureSettingsUpdateSpec struct {
	// Indicates whether this cluster/pod is managed by Horizon Cloud Services. This will be false only when there are no cloud managed machines.
	CloudManaged bool `json:"cloud_managed,omitempty"`
}
