/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2106
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// FarmCreateSpec Information required to create a farm.
type FarmCreateSpec struct {
	// Access groups can organize the entities such as farms in the organization. They can also be used for delegated administration.
	AccessGroupId         string                           `json:"access_group_id"`
	AutomatedFarmSettings *FarmAutomatedSettingsCreateSpec `json:"automated_farm_settings,omitempty"`
	// Description of the farm.
	Description *string `json:"description,omitempty"`
	// Display name of the farm. If the display name is left blank, it defaults to name.
	DisplayName             *string                                `json:"display_name,omitempty"`
	DisplayProtocolSettings *FarmDisplayProtocolSettingsCreateSpec `json:"display_protocol_settings,omitempty"`
	// Indicates whether the farm is enabled for brokering. Default value is true.
	Enabled              *bool                               `json:"enabled,omitempty"`
	LoadBalancerSettings *RDSHLoadBalancerSettingsCreateSpec `json:"load_balancer_settings,omitempty"`
	// Name of the farm. This property must contain only alphanumerics, underscores, and dashes.
	Name string `json:"name"`
	// List of IDs of RDS Servers in the Manual Farm. This is applicable if type is set to MANUAL.
	RdsServerIds *[]string `json:"rds_server_ids,omitempty"`
	// The minimum number of machines that must be fully operational in order to avoid showing the farm in an error state. Default value is 0.
	ServerErrorThreshold *int32                         `json:"server_error_threshold,omitempty"`
	SessionSettings      *FarmSessionSettingsCreateSpec `json:"session_settings,omitempty"`
	// Type of the farm. * AUTOMATED: Automated Farm. * MANUAL: Manual Farm.
	Type string `json:"type"`
	// Indicates whether to use custom scripts for load balancing or not. Default value is false.
	UseCustomScriptForLoadBalancing *bool `json:"use_custom_script_for_load_balancing,omitempty"`
}

// NewFarmCreateSpec instantiates a new FarmCreateSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFarmCreateSpec(accessGroupId string, name string, type_ string) *FarmCreateSpec {
	this := FarmCreateSpec{}
	this.AccessGroupId = accessGroupId
	this.Name = name
	this.Type = type_
	return &this
}

// NewFarmCreateSpecWithDefaults instantiates a new FarmCreateSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFarmCreateSpecWithDefaults() *FarmCreateSpec {
	this := FarmCreateSpec{}
	return &this
}

// GetAccessGroupId returns the AccessGroupId field value
func (o *FarmCreateSpec) GetAccessGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessGroupId
}

// GetAccessGroupIdOk returns a tuple with the AccessGroupId field value
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetAccessGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessGroupId, true
}

// SetAccessGroupId sets field value
func (o *FarmCreateSpec) SetAccessGroupId(v string) {
	o.AccessGroupId = v
}

// GetAutomatedFarmSettings returns the AutomatedFarmSettings field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetAutomatedFarmSettings() FarmAutomatedSettingsCreateSpec {
	if o == nil || o.AutomatedFarmSettings == nil {
		var ret FarmAutomatedSettingsCreateSpec
		return ret
	}
	return *o.AutomatedFarmSettings
}

// GetAutomatedFarmSettingsOk returns a tuple with the AutomatedFarmSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetAutomatedFarmSettingsOk() (*FarmAutomatedSettingsCreateSpec, bool) {
	if o == nil || o.AutomatedFarmSettings == nil {
		return nil, false
	}
	return o.AutomatedFarmSettings, true
}

// HasAutomatedFarmSettings returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasAutomatedFarmSettings() bool {
	if o != nil && o.AutomatedFarmSettings != nil {
		return true
	}

	return false
}

// SetAutomatedFarmSettings gets a reference to the given FarmAutomatedSettingsCreateSpec and assigns it to the AutomatedFarmSettings field.
func (o *FarmCreateSpec) SetAutomatedFarmSettings(v FarmAutomatedSettingsCreateSpec) {
	o.AutomatedFarmSettings = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FarmCreateSpec) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *FarmCreateSpec) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayProtocolSettings returns the DisplayProtocolSettings field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetDisplayProtocolSettings() FarmDisplayProtocolSettingsCreateSpec {
	if o == nil || o.DisplayProtocolSettings == nil {
		var ret FarmDisplayProtocolSettingsCreateSpec
		return ret
	}
	return *o.DisplayProtocolSettings
}

// GetDisplayProtocolSettingsOk returns a tuple with the DisplayProtocolSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetDisplayProtocolSettingsOk() (*FarmDisplayProtocolSettingsCreateSpec, bool) {
	if o == nil || o.DisplayProtocolSettings == nil {
		return nil, false
	}
	return o.DisplayProtocolSettings, true
}

// HasDisplayProtocolSettings returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasDisplayProtocolSettings() bool {
	if o != nil && o.DisplayProtocolSettings != nil {
		return true
	}

	return false
}

// SetDisplayProtocolSettings gets a reference to the given FarmDisplayProtocolSettingsCreateSpec and assigns it to the DisplayProtocolSettings field.
func (o *FarmCreateSpec) SetDisplayProtocolSettings(v FarmDisplayProtocolSettingsCreateSpec) {
	o.DisplayProtocolSettings = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *FarmCreateSpec) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetLoadBalancerSettings returns the LoadBalancerSettings field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetLoadBalancerSettings() RDSHLoadBalancerSettingsCreateSpec {
	if o == nil || o.LoadBalancerSettings == nil {
		var ret RDSHLoadBalancerSettingsCreateSpec
		return ret
	}
	return *o.LoadBalancerSettings
}

// GetLoadBalancerSettingsOk returns a tuple with the LoadBalancerSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetLoadBalancerSettingsOk() (*RDSHLoadBalancerSettingsCreateSpec, bool) {
	if o == nil || o.LoadBalancerSettings == nil {
		return nil, false
	}
	return o.LoadBalancerSettings, true
}

// HasLoadBalancerSettings returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasLoadBalancerSettings() bool {
	if o != nil && o.LoadBalancerSettings != nil {
		return true
	}

	return false
}

// SetLoadBalancerSettings gets a reference to the given RDSHLoadBalancerSettingsCreateSpec and assigns it to the LoadBalancerSettings field.
func (o *FarmCreateSpec) SetLoadBalancerSettings(v RDSHLoadBalancerSettingsCreateSpec) {
	o.LoadBalancerSettings = &v
}

// GetName returns the Name field value
func (o *FarmCreateSpec) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FarmCreateSpec) SetName(v string) {
	o.Name = v
}

// GetRdsServerIds returns the RdsServerIds field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetRdsServerIds() []string {
	if o == nil || o.RdsServerIds == nil {
		var ret []string
		return ret
	}
	return *o.RdsServerIds
}

// GetRdsServerIdsOk returns a tuple with the RdsServerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetRdsServerIdsOk() (*[]string, bool) {
	if o == nil || o.RdsServerIds == nil {
		return nil, false
	}
	return o.RdsServerIds, true
}

// HasRdsServerIds returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasRdsServerIds() bool {
	if o != nil && o.RdsServerIds != nil {
		return true
	}

	return false
}

// SetRdsServerIds gets a reference to the given []string and assigns it to the RdsServerIds field.
func (o *FarmCreateSpec) SetRdsServerIds(v []string) {
	o.RdsServerIds = &v
}

// GetServerErrorThreshold returns the ServerErrorThreshold field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetServerErrorThreshold() int32 {
	if o == nil || o.ServerErrorThreshold == nil {
		var ret int32
		return ret
	}
	return *o.ServerErrorThreshold
}

// GetServerErrorThresholdOk returns a tuple with the ServerErrorThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetServerErrorThresholdOk() (*int32, bool) {
	if o == nil || o.ServerErrorThreshold == nil {
		return nil, false
	}
	return o.ServerErrorThreshold, true
}

// HasServerErrorThreshold returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasServerErrorThreshold() bool {
	if o != nil && o.ServerErrorThreshold != nil {
		return true
	}

	return false
}

// SetServerErrorThreshold gets a reference to the given int32 and assigns it to the ServerErrorThreshold field.
func (o *FarmCreateSpec) SetServerErrorThreshold(v int32) {
	o.ServerErrorThreshold = &v
}

// GetSessionSettings returns the SessionSettings field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetSessionSettings() FarmSessionSettingsCreateSpec {
	if o == nil || o.SessionSettings == nil {
		var ret FarmSessionSettingsCreateSpec
		return ret
	}
	return *o.SessionSettings
}

// GetSessionSettingsOk returns a tuple with the SessionSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetSessionSettingsOk() (*FarmSessionSettingsCreateSpec, bool) {
	if o == nil || o.SessionSettings == nil {
		return nil, false
	}
	return o.SessionSettings, true
}

// HasSessionSettings returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasSessionSettings() bool {
	if o != nil && o.SessionSettings != nil {
		return true
	}

	return false
}

// SetSessionSettings gets a reference to the given FarmSessionSettingsCreateSpec and assigns it to the SessionSettings field.
func (o *FarmCreateSpec) SetSessionSettings(v FarmSessionSettingsCreateSpec) {
	o.SessionSettings = &v
}

// GetType returns the Type field value
func (o *FarmCreateSpec) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FarmCreateSpec) SetType(v string) {
	o.Type = v
}

// GetUseCustomScriptForLoadBalancing returns the UseCustomScriptForLoadBalancing field value if set, zero value otherwise.
func (o *FarmCreateSpec) GetUseCustomScriptForLoadBalancing() bool {
	if o == nil || o.UseCustomScriptForLoadBalancing == nil {
		var ret bool
		return ret
	}
	return *o.UseCustomScriptForLoadBalancing
}

// GetUseCustomScriptForLoadBalancingOk returns a tuple with the UseCustomScriptForLoadBalancing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmCreateSpec) GetUseCustomScriptForLoadBalancingOk() (*bool, bool) {
	if o == nil || o.UseCustomScriptForLoadBalancing == nil {
		return nil, false
	}
	return o.UseCustomScriptForLoadBalancing, true
}

// HasUseCustomScriptForLoadBalancing returns a boolean if a field has been set.
func (o *FarmCreateSpec) HasUseCustomScriptForLoadBalancing() bool {
	if o != nil && o.UseCustomScriptForLoadBalancing != nil {
		return true
	}

	return false
}

// SetUseCustomScriptForLoadBalancing gets a reference to the given bool and assigns it to the UseCustomScriptForLoadBalancing field.
func (o *FarmCreateSpec) SetUseCustomScriptForLoadBalancing(v bool) {
	o.UseCustomScriptForLoadBalancing = &v
}

func (o FarmCreateSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["access_group_id"] = o.AccessGroupId
	}
	if o.AutomatedFarmSettings != nil {
		toSerialize["automated_farm_settings"] = o.AutomatedFarmSettings
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.DisplayName != nil {
		toSerialize["display_name"] = o.DisplayName
	}
	if o.DisplayProtocolSettings != nil {
		toSerialize["display_protocol_settings"] = o.DisplayProtocolSettings
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.LoadBalancerSettings != nil {
		toSerialize["load_balancer_settings"] = o.LoadBalancerSettings
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.RdsServerIds != nil {
		toSerialize["rds_server_ids"] = o.RdsServerIds
	}
	if o.ServerErrorThreshold != nil {
		toSerialize["server_error_threshold"] = o.ServerErrorThreshold
	}
	if o.SessionSettings != nil {
		toSerialize["session_settings"] = o.SessionSettings
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.UseCustomScriptForLoadBalancing != nil {
		toSerialize["use_custom_script_for_load_balancing"] = o.UseCustomScriptForLoadBalancing
	}
	return json.Marshal(toSerialize)
}

type NullableFarmCreateSpec struct {
	value *FarmCreateSpec
	isSet bool
}

func (v NullableFarmCreateSpec) Get() *FarmCreateSpec {
	return v.value
}

func (v *NullableFarmCreateSpec) Set(val *FarmCreateSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableFarmCreateSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableFarmCreateSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFarmCreateSpec(val *FarmCreateSpec) *NullableFarmCreateSpec {
	return &NullableFarmCreateSpec{value: val, isSet: true}
}

func (v NullableFarmCreateSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFarmCreateSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
