/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2111
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// FederationAccessGroupInfo Information about Federation Access Group
type FederationAccessGroupInfo struct {
	// Indicates whether this federation access group can be deleted.
	Deletable *bool `json:"deletable,omitempty"`
	// Federation Access group description.
	Description *string `json:"description,omitempty"`
	// Unique ID representing this Federation Access Group.
	Id *string `json:"id,omitempty"`
	// Federation Access group name.
	Name *string `json:"name,omitempty"`
}

// NewFederationAccessGroupInfo instantiates a new FederationAccessGroupInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationAccessGroupInfo() *FederationAccessGroupInfo {
	this := FederationAccessGroupInfo{}
	return &this
}

// NewFederationAccessGroupInfoWithDefaults instantiates a new FederationAccessGroupInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationAccessGroupInfoWithDefaults() *FederationAccessGroupInfo {
	this := FederationAccessGroupInfo{}
	return &this
}

// GetDeletable returns the Deletable field value if set, zero value otherwise.
func (o *FederationAccessGroupInfo) GetDeletable() bool {
	if o == nil || o.Deletable == nil {
		var ret bool
		return ret
	}
	return *o.Deletable
}

// GetDeletableOk returns a tuple with the Deletable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationAccessGroupInfo) GetDeletableOk() (*bool, bool) {
	if o == nil || o.Deletable == nil {
		return nil, false
	}
	return o.Deletable, true
}

// HasDeletable returns a boolean if a field has been set.
func (o *FederationAccessGroupInfo) HasDeletable() bool {
	if o != nil && o.Deletable != nil {
		return true
	}

	return false
}

// SetDeletable gets a reference to the given bool and assigns it to the Deletable field.
func (o *FederationAccessGroupInfo) SetDeletable(v bool) {
	o.Deletable = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FederationAccessGroupInfo) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationAccessGroupInfo) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FederationAccessGroupInfo) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FederationAccessGroupInfo) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FederationAccessGroupInfo) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationAccessGroupInfo) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FederationAccessGroupInfo) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FederationAccessGroupInfo) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FederationAccessGroupInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationAccessGroupInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FederationAccessGroupInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FederationAccessGroupInfo) SetName(v string) {
	o.Name = &v
}

func (o FederationAccessGroupInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Deletable != nil {
		toSerialize["deletable"] = o.Deletable
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableFederationAccessGroupInfo struct {
	value *FederationAccessGroupInfo
	isSet bool
}

func (v NullableFederationAccessGroupInfo) Get() *FederationAccessGroupInfo {
	return v.value
}

func (v *NullableFederationAccessGroupInfo) Set(val *FederationAccessGroupInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationAccessGroupInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationAccessGroupInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationAccessGroupInfo(val *FederationAccessGroupInfo) *NullableFederationAccessGroupInfo {
	return &NullableFederationAccessGroupInfo{value: val, isSet: true}
}

func (v NullableFederationAccessGroupInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationAccessGroupInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
