/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2106
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// GeneralSettings Information related to General Settings.
type GeneralSettings struct {
	// The time allowed to elapse after a user has authenticated before the application SSO credentials are locked unless the user's Horizon client supports idle sessions and the user remains active.
	ApplicationSsoTimeoutMinutes *int32 `json:"application_sso_timeout_minutes,omitempty"`
	// Specifies the policy for the maximum time after which single sign on will be disabled for application sessions. * DISABLED_AFTER: Single sign on will be disabled after the specified number of minutes has elapsed since the user connected to Horizon Connection Server. * DISABLED: Single sign on is disabled. * ENABLED: Single sign on is enabled.
	ApplicationSsoTimeoutPolicy string `json:"application_sso_timeout_policy"`
	// Indicates whether restricted Horizon clients should be blocked by the Connection Server.
	BlockRestrictedClients *bool `json:"block_restricted_clients,omitempty"`
	// Determines how long a user can be idle before the Connection Server takes measure to protect the session.
	ClientIdleSessionTimeoutMinutes *int32 `json:"client_idle_session_timeout_minutes,omitempty"`
	// Specifies the policy for the maximum time that a that a user can be idle before the Connection Server takes measure to protect the session. * TIMEOUT_AFTER: The timeout is set for a configurable time. * NEVER: The timeout has been disabled.
	ClientIdleSessionTimeoutPolicy string `json:"client_idle_session_timeout_policy"`
	// Determines how long a user can keep a session open after logging in to the Connection Server. When a session times out, the session is terminated and the Horizon client is disconnected from the resource. This property has a default value of 600 and a minimum value of 5. This property is required if clientMaxSessionTimeoutPolicy is set to TIMEOUT_AFTER.
	ClientMaxSessionTimeoutMinutes *int32 `json:"client_max_session_timeout_minutes,omitempty"`
	// Client max session lifetime policy. This property has a default value of TIMEOUT_AFTER. A value of TIMEOUT_AFTER indicates that the Horizon client session times out after a configurable session length. A value of NEVER indicates that the Horizon client session will not time out and will only end due to inactivity. * TIMEOUT_AFTER: The timeout is set for a configurable time. * NEVER: The timeout has been disabled.
	ClientMaxSessionTimeoutPolicy string `json:"client_max_session_timeout_policy"`
	// Determines the maximum length of time that a session will be kept active if there is no traffic between the Horizon client and the Connection Server.
	ClientSessionTimeoutMinutes int32 `json:"client_session_timeout_minutes"`
	// Determines how long an idle admin console session continues before the session times out.
	ConsoleSessionTimeoutMinutes *int32 `json:"console_session_timeout_minutes,omitempty"`
	// Indicates whether to show a disclaimer or other message when the Horizon Client user logs in. This change will take effect on next login for each user.
	DisplayPreLoginMessage *bool `json:"display_pre_login_message,omitempty"`
	// Indicates whether to display a warning message when users are forced to log off because a scheduled or immediate update such as a machine-refresh operation is about to start.
	DisplayWarningBeforeForcedLogoff *bool `json:"display_warning_before_forced_logoff,omitempty"`
	// Enable updation of the global status of the application periodically. The Dashboard Information is also updated at regular intervals when Dashboard page is active.
	EnableAutomaticStatusUpdates *bool `json:"enable_automatic_status_updates,omitempty"`
	// Indicates whether to clean up session credentials when one tab connecting to remote machine/application is closed.
	EnableCredentialCleanupForHtmlaccess *bool `json:"enable_credential_cleanup_for_htmlaccess,omitempty"`
	// Enables 2 factor re-authentication after idle session timeout.
	EnableMultiFactorReAuthentication *bool `json:"enable_multi_factor_re_authentication,omitempty"`
	// Indicates whether the domain list will be sent to the Horizon client. Since domain list will be sent before user is authenticated with server, it could disclose domain information to external users.
	EnableSendingDomainList *bool `json:"enable_sending_domain_list,omitempty"`
	// Permits RDSServer operating systems to be used for non-RDS Machines.
	EnableServerInSingleUserMode *bool `json:"enable_server_in_single_user_mode,omitempty"`
	// The warning to be displayed before logging off the user.
	ForcedLogoffMessage *string `json:"forced_logoff_message,omitempty"`
	// The time to wait after the warning is displayed and before logging off the user.
	ForcedLogoffTimeoutMinutes *int32 `json:"forced_logoff_timeout_minutes,omitempty"`
	// Whether to hide the list of domains in the Horizon client user interface. If value set to true, the user will need to provide a UPN (e.g. user@domain) or a logon name in the format domain\\\\user when logging in.
	HideDomainListInClient *bool `json:"hide_domain_list_in_client,omitempty"`
	// Indicates whether to hide the server URL in the Horizon client user interface.
	HideServerInformationInClient *bool `json:"hide_server_information_in_client,omitempty"`
	// Single sign on will be disabled after the specified time has elapsed since the user connected to Connection Server.
	MachineSsoTimeoutMinutes *int32 `json:"machine_sso_timeout_minutes,omitempty"`
	// Specifies the policy for the maximum time after which single sign on will be disabled after a user connects to the Connection Server. * DISABLED_AFTER: Single sign on will be disabled after the specified number of minutes has elapsed since the user connected to Horizon Connection Server. * DISABLED: Single sign on is disabled. * ENABLED: Single sign on is enabled.
	MachineSsoTimeoutPolicy string `json:"machine_sso_timeout_policy"`
	// Displays a disclaimer or another message to Horizon Client users when they log in. No message will be displayed if this is not set.
	PreLoginMessage *string `json:"pre_login_message,omitempty"`
	// List of restricted Horizon Clients.
	RestrictedClientData *[]RestrictedClientData `json:"restricted_client_data,omitempty"`
	// The message to be displayed to Horizon clients which are blocked by the Connection Server.
	RestrictedClientMessage *string `json:"restricted_client_message,omitempty"`
	// Determines whether or not to store the RDS Per Device Client Access License on Horizon client devices. This value can be true only if Store Client Access License on Connection Server is true.
	StoreCalOnClient bool `json:"store_cal_on_client"`
	// Determines whether or not to store the RDS Per Device Client Access License on Connection Server.
	StoreCalOnConnectionServer bool `json:"store_cal_on_connection_server"`
}

// NewGeneralSettings instantiates a new GeneralSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneralSettings(applicationSsoTimeoutPolicy string, clientIdleSessionTimeoutPolicy string, clientMaxSessionTimeoutPolicy string, clientSessionTimeoutMinutes int32, machineSsoTimeoutPolicy string, storeCalOnClient bool, storeCalOnConnectionServer bool) *GeneralSettings {
	this := GeneralSettings{}
	this.ApplicationSsoTimeoutPolicy = applicationSsoTimeoutPolicy
	this.ClientIdleSessionTimeoutPolicy = clientIdleSessionTimeoutPolicy
	this.ClientMaxSessionTimeoutPolicy = clientMaxSessionTimeoutPolicy
	this.ClientSessionTimeoutMinutes = clientSessionTimeoutMinutes
	this.MachineSsoTimeoutPolicy = machineSsoTimeoutPolicy
	this.StoreCalOnClient = storeCalOnClient
	this.StoreCalOnConnectionServer = storeCalOnConnectionServer
	return &this
}

// NewGeneralSettingsWithDefaults instantiates a new GeneralSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneralSettingsWithDefaults() *GeneralSettings {
	this := GeneralSettings{}
	return &this
}

// GetApplicationSsoTimeoutMinutes returns the ApplicationSsoTimeoutMinutes field value if set, zero value otherwise.
func (o *GeneralSettings) GetApplicationSsoTimeoutMinutes() int32 {
	if o == nil || o.ApplicationSsoTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.ApplicationSsoTimeoutMinutes
}

// GetApplicationSsoTimeoutMinutesOk returns a tuple with the ApplicationSsoTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetApplicationSsoTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.ApplicationSsoTimeoutMinutes == nil {
		return nil, false
	}
	return o.ApplicationSsoTimeoutMinutes, true
}

// HasApplicationSsoTimeoutMinutes returns a boolean if a field has been set.
func (o *GeneralSettings) HasApplicationSsoTimeoutMinutes() bool {
	if o != nil && o.ApplicationSsoTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetApplicationSsoTimeoutMinutes gets a reference to the given int32 and assigns it to the ApplicationSsoTimeoutMinutes field.
func (o *GeneralSettings) SetApplicationSsoTimeoutMinutes(v int32) {
	o.ApplicationSsoTimeoutMinutes = &v
}

// GetApplicationSsoTimeoutPolicy returns the ApplicationSsoTimeoutPolicy field value
func (o *GeneralSettings) GetApplicationSsoTimeoutPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationSsoTimeoutPolicy
}

// GetApplicationSsoTimeoutPolicyOk returns a tuple with the ApplicationSsoTimeoutPolicy field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetApplicationSsoTimeoutPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationSsoTimeoutPolicy, true
}

// SetApplicationSsoTimeoutPolicy sets field value
func (o *GeneralSettings) SetApplicationSsoTimeoutPolicy(v string) {
	o.ApplicationSsoTimeoutPolicy = v
}

// GetBlockRestrictedClients returns the BlockRestrictedClients field value if set, zero value otherwise.
func (o *GeneralSettings) GetBlockRestrictedClients() bool {
	if o == nil || o.BlockRestrictedClients == nil {
		var ret bool
		return ret
	}
	return *o.BlockRestrictedClients
}

// GetBlockRestrictedClientsOk returns a tuple with the BlockRestrictedClients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetBlockRestrictedClientsOk() (*bool, bool) {
	if o == nil || o.BlockRestrictedClients == nil {
		return nil, false
	}
	return o.BlockRestrictedClients, true
}

// HasBlockRestrictedClients returns a boolean if a field has been set.
func (o *GeneralSettings) HasBlockRestrictedClients() bool {
	if o != nil && o.BlockRestrictedClients != nil {
		return true
	}

	return false
}

// SetBlockRestrictedClients gets a reference to the given bool and assigns it to the BlockRestrictedClients field.
func (o *GeneralSettings) SetBlockRestrictedClients(v bool) {
	o.BlockRestrictedClients = &v
}

// GetClientIdleSessionTimeoutMinutes returns the ClientIdleSessionTimeoutMinutes field value if set, zero value otherwise.
func (o *GeneralSettings) GetClientIdleSessionTimeoutMinutes() int32 {
	if o == nil || o.ClientIdleSessionTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.ClientIdleSessionTimeoutMinutes
}

// GetClientIdleSessionTimeoutMinutesOk returns a tuple with the ClientIdleSessionTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetClientIdleSessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.ClientIdleSessionTimeoutMinutes == nil {
		return nil, false
	}
	return o.ClientIdleSessionTimeoutMinutes, true
}

// HasClientIdleSessionTimeoutMinutes returns a boolean if a field has been set.
func (o *GeneralSettings) HasClientIdleSessionTimeoutMinutes() bool {
	if o != nil && o.ClientIdleSessionTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetClientIdleSessionTimeoutMinutes gets a reference to the given int32 and assigns it to the ClientIdleSessionTimeoutMinutes field.
func (o *GeneralSettings) SetClientIdleSessionTimeoutMinutes(v int32) {
	o.ClientIdleSessionTimeoutMinutes = &v
}

// GetClientIdleSessionTimeoutPolicy returns the ClientIdleSessionTimeoutPolicy field value
func (o *GeneralSettings) GetClientIdleSessionTimeoutPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientIdleSessionTimeoutPolicy
}

// GetClientIdleSessionTimeoutPolicyOk returns a tuple with the ClientIdleSessionTimeoutPolicy field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetClientIdleSessionTimeoutPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientIdleSessionTimeoutPolicy, true
}

// SetClientIdleSessionTimeoutPolicy sets field value
func (o *GeneralSettings) SetClientIdleSessionTimeoutPolicy(v string) {
	o.ClientIdleSessionTimeoutPolicy = v
}

// GetClientMaxSessionTimeoutMinutes returns the ClientMaxSessionTimeoutMinutes field value if set, zero value otherwise.
func (o *GeneralSettings) GetClientMaxSessionTimeoutMinutes() int32 {
	if o == nil || o.ClientMaxSessionTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.ClientMaxSessionTimeoutMinutes
}

// GetClientMaxSessionTimeoutMinutesOk returns a tuple with the ClientMaxSessionTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetClientMaxSessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.ClientMaxSessionTimeoutMinutes == nil {
		return nil, false
	}
	return o.ClientMaxSessionTimeoutMinutes, true
}

// HasClientMaxSessionTimeoutMinutes returns a boolean if a field has been set.
func (o *GeneralSettings) HasClientMaxSessionTimeoutMinutes() bool {
	if o != nil && o.ClientMaxSessionTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetClientMaxSessionTimeoutMinutes gets a reference to the given int32 and assigns it to the ClientMaxSessionTimeoutMinutes field.
func (o *GeneralSettings) SetClientMaxSessionTimeoutMinutes(v int32) {
	o.ClientMaxSessionTimeoutMinutes = &v
}

// GetClientMaxSessionTimeoutPolicy returns the ClientMaxSessionTimeoutPolicy field value
func (o *GeneralSettings) GetClientMaxSessionTimeoutPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientMaxSessionTimeoutPolicy
}

// GetClientMaxSessionTimeoutPolicyOk returns a tuple with the ClientMaxSessionTimeoutPolicy field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetClientMaxSessionTimeoutPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientMaxSessionTimeoutPolicy, true
}

// SetClientMaxSessionTimeoutPolicy sets field value
func (o *GeneralSettings) SetClientMaxSessionTimeoutPolicy(v string) {
	o.ClientMaxSessionTimeoutPolicy = v
}

// GetClientSessionTimeoutMinutes returns the ClientSessionTimeoutMinutes field value
func (o *GeneralSettings) GetClientSessionTimeoutMinutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ClientSessionTimeoutMinutes
}

// GetClientSessionTimeoutMinutesOk returns a tuple with the ClientSessionTimeoutMinutes field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetClientSessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSessionTimeoutMinutes, true
}

// SetClientSessionTimeoutMinutes sets field value
func (o *GeneralSettings) SetClientSessionTimeoutMinutes(v int32) {
	o.ClientSessionTimeoutMinutes = v
}

// GetConsoleSessionTimeoutMinutes returns the ConsoleSessionTimeoutMinutes field value if set, zero value otherwise.
func (o *GeneralSettings) GetConsoleSessionTimeoutMinutes() int32 {
	if o == nil || o.ConsoleSessionTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.ConsoleSessionTimeoutMinutes
}

// GetConsoleSessionTimeoutMinutesOk returns a tuple with the ConsoleSessionTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetConsoleSessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.ConsoleSessionTimeoutMinutes == nil {
		return nil, false
	}
	return o.ConsoleSessionTimeoutMinutes, true
}

// HasConsoleSessionTimeoutMinutes returns a boolean if a field has been set.
func (o *GeneralSettings) HasConsoleSessionTimeoutMinutes() bool {
	if o != nil && o.ConsoleSessionTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetConsoleSessionTimeoutMinutes gets a reference to the given int32 and assigns it to the ConsoleSessionTimeoutMinutes field.
func (o *GeneralSettings) SetConsoleSessionTimeoutMinutes(v int32) {
	o.ConsoleSessionTimeoutMinutes = &v
}

// GetDisplayPreLoginMessage returns the DisplayPreLoginMessage field value if set, zero value otherwise.
func (o *GeneralSettings) GetDisplayPreLoginMessage() bool {
	if o == nil || o.DisplayPreLoginMessage == nil {
		var ret bool
		return ret
	}
	return *o.DisplayPreLoginMessage
}

// GetDisplayPreLoginMessageOk returns a tuple with the DisplayPreLoginMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetDisplayPreLoginMessageOk() (*bool, bool) {
	if o == nil || o.DisplayPreLoginMessage == nil {
		return nil, false
	}
	return o.DisplayPreLoginMessage, true
}

// HasDisplayPreLoginMessage returns a boolean if a field has been set.
func (o *GeneralSettings) HasDisplayPreLoginMessage() bool {
	if o != nil && o.DisplayPreLoginMessage != nil {
		return true
	}

	return false
}

// SetDisplayPreLoginMessage gets a reference to the given bool and assigns it to the DisplayPreLoginMessage field.
func (o *GeneralSettings) SetDisplayPreLoginMessage(v bool) {
	o.DisplayPreLoginMessage = &v
}

// GetDisplayWarningBeforeForcedLogoff returns the DisplayWarningBeforeForcedLogoff field value if set, zero value otherwise.
func (o *GeneralSettings) GetDisplayWarningBeforeForcedLogoff() bool {
	if o == nil || o.DisplayWarningBeforeForcedLogoff == nil {
		var ret bool
		return ret
	}
	return *o.DisplayWarningBeforeForcedLogoff
}

// GetDisplayWarningBeforeForcedLogoffOk returns a tuple with the DisplayWarningBeforeForcedLogoff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetDisplayWarningBeforeForcedLogoffOk() (*bool, bool) {
	if o == nil || o.DisplayWarningBeforeForcedLogoff == nil {
		return nil, false
	}
	return o.DisplayWarningBeforeForcedLogoff, true
}

// HasDisplayWarningBeforeForcedLogoff returns a boolean if a field has been set.
func (o *GeneralSettings) HasDisplayWarningBeforeForcedLogoff() bool {
	if o != nil && o.DisplayWarningBeforeForcedLogoff != nil {
		return true
	}

	return false
}

// SetDisplayWarningBeforeForcedLogoff gets a reference to the given bool and assigns it to the DisplayWarningBeforeForcedLogoff field.
func (o *GeneralSettings) SetDisplayWarningBeforeForcedLogoff(v bool) {
	o.DisplayWarningBeforeForcedLogoff = &v
}

// GetEnableAutomaticStatusUpdates returns the EnableAutomaticStatusUpdates field value if set, zero value otherwise.
func (o *GeneralSettings) GetEnableAutomaticStatusUpdates() bool {
	if o == nil || o.EnableAutomaticStatusUpdates == nil {
		var ret bool
		return ret
	}
	return *o.EnableAutomaticStatusUpdates
}

// GetEnableAutomaticStatusUpdatesOk returns a tuple with the EnableAutomaticStatusUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetEnableAutomaticStatusUpdatesOk() (*bool, bool) {
	if o == nil || o.EnableAutomaticStatusUpdates == nil {
		return nil, false
	}
	return o.EnableAutomaticStatusUpdates, true
}

// HasEnableAutomaticStatusUpdates returns a boolean if a field has been set.
func (o *GeneralSettings) HasEnableAutomaticStatusUpdates() bool {
	if o != nil && o.EnableAutomaticStatusUpdates != nil {
		return true
	}

	return false
}

// SetEnableAutomaticStatusUpdates gets a reference to the given bool and assigns it to the EnableAutomaticStatusUpdates field.
func (o *GeneralSettings) SetEnableAutomaticStatusUpdates(v bool) {
	o.EnableAutomaticStatusUpdates = &v
}

// GetEnableCredentialCleanupForHtmlaccess returns the EnableCredentialCleanupForHtmlaccess field value if set, zero value otherwise.
func (o *GeneralSettings) GetEnableCredentialCleanupForHtmlaccess() bool {
	if o == nil || o.EnableCredentialCleanupForHtmlaccess == nil {
		var ret bool
		return ret
	}
	return *o.EnableCredentialCleanupForHtmlaccess
}

// GetEnableCredentialCleanupForHtmlaccessOk returns a tuple with the EnableCredentialCleanupForHtmlaccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetEnableCredentialCleanupForHtmlaccessOk() (*bool, bool) {
	if o == nil || o.EnableCredentialCleanupForHtmlaccess == nil {
		return nil, false
	}
	return o.EnableCredentialCleanupForHtmlaccess, true
}

// HasEnableCredentialCleanupForHtmlaccess returns a boolean if a field has been set.
func (o *GeneralSettings) HasEnableCredentialCleanupForHtmlaccess() bool {
	if o != nil && o.EnableCredentialCleanupForHtmlaccess != nil {
		return true
	}

	return false
}

// SetEnableCredentialCleanupForHtmlaccess gets a reference to the given bool and assigns it to the EnableCredentialCleanupForHtmlaccess field.
func (o *GeneralSettings) SetEnableCredentialCleanupForHtmlaccess(v bool) {
	o.EnableCredentialCleanupForHtmlaccess = &v
}

// GetEnableMultiFactorReAuthentication returns the EnableMultiFactorReAuthentication field value if set, zero value otherwise.
func (o *GeneralSettings) GetEnableMultiFactorReAuthentication() bool {
	if o == nil || o.EnableMultiFactorReAuthentication == nil {
		var ret bool
		return ret
	}
	return *o.EnableMultiFactorReAuthentication
}

// GetEnableMultiFactorReAuthenticationOk returns a tuple with the EnableMultiFactorReAuthentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetEnableMultiFactorReAuthenticationOk() (*bool, bool) {
	if o == nil || o.EnableMultiFactorReAuthentication == nil {
		return nil, false
	}
	return o.EnableMultiFactorReAuthentication, true
}

// HasEnableMultiFactorReAuthentication returns a boolean if a field has been set.
func (o *GeneralSettings) HasEnableMultiFactorReAuthentication() bool {
	if o != nil && o.EnableMultiFactorReAuthentication != nil {
		return true
	}

	return false
}

// SetEnableMultiFactorReAuthentication gets a reference to the given bool and assigns it to the EnableMultiFactorReAuthentication field.
func (o *GeneralSettings) SetEnableMultiFactorReAuthentication(v bool) {
	o.EnableMultiFactorReAuthentication = &v
}

// GetEnableSendingDomainList returns the EnableSendingDomainList field value if set, zero value otherwise.
func (o *GeneralSettings) GetEnableSendingDomainList() bool {
	if o == nil || o.EnableSendingDomainList == nil {
		var ret bool
		return ret
	}
	return *o.EnableSendingDomainList
}

// GetEnableSendingDomainListOk returns a tuple with the EnableSendingDomainList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetEnableSendingDomainListOk() (*bool, bool) {
	if o == nil || o.EnableSendingDomainList == nil {
		return nil, false
	}
	return o.EnableSendingDomainList, true
}

// HasEnableSendingDomainList returns a boolean if a field has been set.
func (o *GeneralSettings) HasEnableSendingDomainList() bool {
	if o != nil && o.EnableSendingDomainList != nil {
		return true
	}

	return false
}

// SetEnableSendingDomainList gets a reference to the given bool and assigns it to the EnableSendingDomainList field.
func (o *GeneralSettings) SetEnableSendingDomainList(v bool) {
	o.EnableSendingDomainList = &v
}

// GetEnableServerInSingleUserMode returns the EnableServerInSingleUserMode field value if set, zero value otherwise.
func (o *GeneralSettings) GetEnableServerInSingleUserMode() bool {
	if o == nil || o.EnableServerInSingleUserMode == nil {
		var ret bool
		return ret
	}
	return *o.EnableServerInSingleUserMode
}

// GetEnableServerInSingleUserModeOk returns a tuple with the EnableServerInSingleUserMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetEnableServerInSingleUserModeOk() (*bool, bool) {
	if o == nil || o.EnableServerInSingleUserMode == nil {
		return nil, false
	}
	return o.EnableServerInSingleUserMode, true
}

// HasEnableServerInSingleUserMode returns a boolean if a field has been set.
func (o *GeneralSettings) HasEnableServerInSingleUserMode() bool {
	if o != nil && o.EnableServerInSingleUserMode != nil {
		return true
	}

	return false
}

// SetEnableServerInSingleUserMode gets a reference to the given bool and assigns it to the EnableServerInSingleUserMode field.
func (o *GeneralSettings) SetEnableServerInSingleUserMode(v bool) {
	o.EnableServerInSingleUserMode = &v
}

// GetForcedLogoffMessage returns the ForcedLogoffMessage field value if set, zero value otherwise.
func (o *GeneralSettings) GetForcedLogoffMessage() string {
	if o == nil || o.ForcedLogoffMessage == nil {
		var ret string
		return ret
	}
	return *o.ForcedLogoffMessage
}

// GetForcedLogoffMessageOk returns a tuple with the ForcedLogoffMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetForcedLogoffMessageOk() (*string, bool) {
	if o == nil || o.ForcedLogoffMessage == nil {
		return nil, false
	}
	return o.ForcedLogoffMessage, true
}

// HasForcedLogoffMessage returns a boolean if a field has been set.
func (o *GeneralSettings) HasForcedLogoffMessage() bool {
	if o != nil && o.ForcedLogoffMessage != nil {
		return true
	}

	return false
}

// SetForcedLogoffMessage gets a reference to the given string and assigns it to the ForcedLogoffMessage field.
func (o *GeneralSettings) SetForcedLogoffMessage(v string) {
	o.ForcedLogoffMessage = &v
}

// GetForcedLogoffTimeoutMinutes returns the ForcedLogoffTimeoutMinutes field value if set, zero value otherwise.
func (o *GeneralSettings) GetForcedLogoffTimeoutMinutes() int32 {
	if o == nil || o.ForcedLogoffTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.ForcedLogoffTimeoutMinutes
}

// GetForcedLogoffTimeoutMinutesOk returns a tuple with the ForcedLogoffTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetForcedLogoffTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.ForcedLogoffTimeoutMinutes == nil {
		return nil, false
	}
	return o.ForcedLogoffTimeoutMinutes, true
}

// HasForcedLogoffTimeoutMinutes returns a boolean if a field has been set.
func (o *GeneralSettings) HasForcedLogoffTimeoutMinutes() bool {
	if o != nil && o.ForcedLogoffTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetForcedLogoffTimeoutMinutes gets a reference to the given int32 and assigns it to the ForcedLogoffTimeoutMinutes field.
func (o *GeneralSettings) SetForcedLogoffTimeoutMinutes(v int32) {
	o.ForcedLogoffTimeoutMinutes = &v
}

// GetHideDomainListInClient returns the HideDomainListInClient field value if set, zero value otherwise.
func (o *GeneralSettings) GetHideDomainListInClient() bool {
	if o == nil || o.HideDomainListInClient == nil {
		var ret bool
		return ret
	}
	return *o.HideDomainListInClient
}

// GetHideDomainListInClientOk returns a tuple with the HideDomainListInClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetHideDomainListInClientOk() (*bool, bool) {
	if o == nil || o.HideDomainListInClient == nil {
		return nil, false
	}
	return o.HideDomainListInClient, true
}

// HasHideDomainListInClient returns a boolean if a field has been set.
func (o *GeneralSettings) HasHideDomainListInClient() bool {
	if o != nil && o.HideDomainListInClient != nil {
		return true
	}

	return false
}

// SetHideDomainListInClient gets a reference to the given bool and assigns it to the HideDomainListInClient field.
func (o *GeneralSettings) SetHideDomainListInClient(v bool) {
	o.HideDomainListInClient = &v
}

// GetHideServerInformationInClient returns the HideServerInformationInClient field value if set, zero value otherwise.
func (o *GeneralSettings) GetHideServerInformationInClient() bool {
	if o == nil || o.HideServerInformationInClient == nil {
		var ret bool
		return ret
	}
	return *o.HideServerInformationInClient
}

// GetHideServerInformationInClientOk returns a tuple with the HideServerInformationInClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetHideServerInformationInClientOk() (*bool, bool) {
	if o == nil || o.HideServerInformationInClient == nil {
		return nil, false
	}
	return o.HideServerInformationInClient, true
}

// HasHideServerInformationInClient returns a boolean if a field has been set.
func (o *GeneralSettings) HasHideServerInformationInClient() bool {
	if o != nil && o.HideServerInformationInClient != nil {
		return true
	}

	return false
}

// SetHideServerInformationInClient gets a reference to the given bool and assigns it to the HideServerInformationInClient field.
func (o *GeneralSettings) SetHideServerInformationInClient(v bool) {
	o.HideServerInformationInClient = &v
}

// GetMachineSsoTimeoutMinutes returns the MachineSsoTimeoutMinutes field value if set, zero value otherwise.
func (o *GeneralSettings) GetMachineSsoTimeoutMinutes() int32 {
	if o == nil || o.MachineSsoTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.MachineSsoTimeoutMinutes
}

// GetMachineSsoTimeoutMinutesOk returns a tuple with the MachineSsoTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetMachineSsoTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.MachineSsoTimeoutMinutes == nil {
		return nil, false
	}
	return o.MachineSsoTimeoutMinutes, true
}

// HasMachineSsoTimeoutMinutes returns a boolean if a field has been set.
func (o *GeneralSettings) HasMachineSsoTimeoutMinutes() bool {
	if o != nil && o.MachineSsoTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetMachineSsoTimeoutMinutes gets a reference to the given int32 and assigns it to the MachineSsoTimeoutMinutes field.
func (o *GeneralSettings) SetMachineSsoTimeoutMinutes(v int32) {
	o.MachineSsoTimeoutMinutes = &v
}

// GetMachineSsoTimeoutPolicy returns the MachineSsoTimeoutPolicy field value
func (o *GeneralSettings) GetMachineSsoTimeoutPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineSsoTimeoutPolicy
}

// GetMachineSsoTimeoutPolicyOk returns a tuple with the MachineSsoTimeoutPolicy field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetMachineSsoTimeoutPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineSsoTimeoutPolicy, true
}

// SetMachineSsoTimeoutPolicy sets field value
func (o *GeneralSettings) SetMachineSsoTimeoutPolicy(v string) {
	o.MachineSsoTimeoutPolicy = v
}

// GetPreLoginMessage returns the PreLoginMessage field value if set, zero value otherwise.
func (o *GeneralSettings) GetPreLoginMessage() string {
	if o == nil || o.PreLoginMessage == nil {
		var ret string
		return ret
	}
	return *o.PreLoginMessage
}

// GetPreLoginMessageOk returns a tuple with the PreLoginMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetPreLoginMessageOk() (*string, bool) {
	if o == nil || o.PreLoginMessage == nil {
		return nil, false
	}
	return o.PreLoginMessage, true
}

// HasPreLoginMessage returns a boolean if a field has been set.
func (o *GeneralSettings) HasPreLoginMessage() bool {
	if o != nil && o.PreLoginMessage != nil {
		return true
	}

	return false
}

// SetPreLoginMessage gets a reference to the given string and assigns it to the PreLoginMessage field.
func (o *GeneralSettings) SetPreLoginMessage(v string) {
	o.PreLoginMessage = &v
}

// GetRestrictedClientData returns the RestrictedClientData field value if set, zero value otherwise.
func (o *GeneralSettings) GetRestrictedClientData() []RestrictedClientData {
	if o == nil || o.RestrictedClientData == nil {
		var ret []RestrictedClientData
		return ret
	}
	return *o.RestrictedClientData
}

// GetRestrictedClientDataOk returns a tuple with the RestrictedClientData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetRestrictedClientDataOk() (*[]RestrictedClientData, bool) {
	if o == nil || o.RestrictedClientData == nil {
		return nil, false
	}
	return o.RestrictedClientData, true
}

// HasRestrictedClientData returns a boolean if a field has been set.
func (o *GeneralSettings) HasRestrictedClientData() bool {
	if o != nil && o.RestrictedClientData != nil {
		return true
	}

	return false
}

// SetRestrictedClientData gets a reference to the given []RestrictedClientData and assigns it to the RestrictedClientData field.
func (o *GeneralSettings) SetRestrictedClientData(v []RestrictedClientData) {
	o.RestrictedClientData = &v
}

// GetRestrictedClientMessage returns the RestrictedClientMessage field value if set, zero value otherwise.
func (o *GeneralSettings) GetRestrictedClientMessage() string {
	if o == nil || o.RestrictedClientMessage == nil {
		var ret string
		return ret
	}
	return *o.RestrictedClientMessage
}

// GetRestrictedClientMessageOk returns a tuple with the RestrictedClientMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetRestrictedClientMessageOk() (*string, bool) {
	if o == nil || o.RestrictedClientMessage == nil {
		return nil, false
	}
	return o.RestrictedClientMessage, true
}

// HasRestrictedClientMessage returns a boolean if a field has been set.
func (o *GeneralSettings) HasRestrictedClientMessage() bool {
	if o != nil && o.RestrictedClientMessage != nil {
		return true
	}

	return false
}

// SetRestrictedClientMessage gets a reference to the given string and assigns it to the RestrictedClientMessage field.
func (o *GeneralSettings) SetRestrictedClientMessage(v string) {
	o.RestrictedClientMessage = &v
}

// GetStoreCalOnClient returns the StoreCalOnClient field value
func (o *GeneralSettings) GetStoreCalOnClient() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StoreCalOnClient
}

// GetStoreCalOnClientOk returns a tuple with the StoreCalOnClient field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetStoreCalOnClientOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreCalOnClient, true
}

// SetStoreCalOnClient sets field value
func (o *GeneralSettings) SetStoreCalOnClient(v bool) {
	o.StoreCalOnClient = v
}

// GetStoreCalOnConnectionServer returns the StoreCalOnConnectionServer field value
func (o *GeneralSettings) GetStoreCalOnConnectionServer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StoreCalOnConnectionServer
}

// GetStoreCalOnConnectionServerOk returns a tuple with the StoreCalOnConnectionServer field value
// and a boolean to check if the value has been set.
func (o *GeneralSettings) GetStoreCalOnConnectionServerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreCalOnConnectionServer, true
}

// SetStoreCalOnConnectionServer sets field value
func (o *GeneralSettings) SetStoreCalOnConnectionServer(v bool) {
	o.StoreCalOnConnectionServer = v
}

func (o GeneralSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApplicationSsoTimeoutMinutes != nil {
		toSerialize["application_sso_timeout_minutes"] = o.ApplicationSsoTimeoutMinutes
	}
	if true {
		toSerialize["application_sso_timeout_policy"] = o.ApplicationSsoTimeoutPolicy
	}
	if o.BlockRestrictedClients != nil {
		toSerialize["block_restricted_clients"] = o.BlockRestrictedClients
	}
	if o.ClientIdleSessionTimeoutMinutes != nil {
		toSerialize["client_idle_session_timeout_minutes"] = o.ClientIdleSessionTimeoutMinutes
	}
	if true {
		toSerialize["client_idle_session_timeout_policy"] = o.ClientIdleSessionTimeoutPolicy
	}
	if o.ClientMaxSessionTimeoutMinutes != nil {
		toSerialize["client_max_session_timeout_minutes"] = o.ClientMaxSessionTimeoutMinutes
	}
	if true {
		toSerialize["client_max_session_timeout_policy"] = o.ClientMaxSessionTimeoutPolicy
	}
	if true {
		toSerialize["client_session_timeout_minutes"] = o.ClientSessionTimeoutMinutes
	}
	if o.ConsoleSessionTimeoutMinutes != nil {
		toSerialize["console_session_timeout_minutes"] = o.ConsoleSessionTimeoutMinutes
	}
	if o.DisplayPreLoginMessage != nil {
		toSerialize["display_pre_login_message"] = o.DisplayPreLoginMessage
	}
	if o.DisplayWarningBeforeForcedLogoff != nil {
		toSerialize["display_warning_before_forced_logoff"] = o.DisplayWarningBeforeForcedLogoff
	}
	if o.EnableAutomaticStatusUpdates != nil {
		toSerialize["enable_automatic_status_updates"] = o.EnableAutomaticStatusUpdates
	}
	if o.EnableCredentialCleanupForHtmlaccess != nil {
		toSerialize["enable_credential_cleanup_for_htmlaccess"] = o.EnableCredentialCleanupForHtmlaccess
	}
	if o.EnableMultiFactorReAuthentication != nil {
		toSerialize["enable_multi_factor_re_authentication"] = o.EnableMultiFactorReAuthentication
	}
	if o.EnableSendingDomainList != nil {
		toSerialize["enable_sending_domain_list"] = o.EnableSendingDomainList
	}
	if o.EnableServerInSingleUserMode != nil {
		toSerialize["enable_server_in_single_user_mode"] = o.EnableServerInSingleUserMode
	}
	if o.ForcedLogoffMessage != nil {
		toSerialize["forced_logoff_message"] = o.ForcedLogoffMessage
	}
	if o.ForcedLogoffTimeoutMinutes != nil {
		toSerialize["forced_logoff_timeout_minutes"] = o.ForcedLogoffTimeoutMinutes
	}
	if o.HideDomainListInClient != nil {
		toSerialize["hide_domain_list_in_client"] = o.HideDomainListInClient
	}
	if o.HideServerInformationInClient != nil {
		toSerialize["hide_server_information_in_client"] = o.HideServerInformationInClient
	}
	if o.MachineSsoTimeoutMinutes != nil {
		toSerialize["machine_sso_timeout_minutes"] = o.MachineSsoTimeoutMinutes
	}
	if true {
		toSerialize["machine_sso_timeout_policy"] = o.MachineSsoTimeoutPolicy
	}
	if o.PreLoginMessage != nil {
		toSerialize["pre_login_message"] = o.PreLoginMessage
	}
	if o.RestrictedClientData != nil {
		toSerialize["restricted_client_data"] = o.RestrictedClientData
	}
	if o.RestrictedClientMessage != nil {
		toSerialize["restricted_client_message"] = o.RestrictedClientMessage
	}
	if true {
		toSerialize["store_cal_on_client"] = o.StoreCalOnClient
	}
	if true {
		toSerialize["store_cal_on_connection_server"] = o.StoreCalOnConnectionServer
	}
	return json.Marshal(toSerialize)
}

type NullableGeneralSettings struct {
	value *GeneralSettings
	isSet bool
}

func (v NullableGeneralSettings) Get() *GeneralSettings {
	return v.value
}

func (v *NullableGeneralSettings) Set(val *GeneralSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneralSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneralSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneralSettings(val *GeneralSettings) *NullableGeneralSettings {
	return &NullableGeneralSettings{value: val, isSet: true}
}

func (v NullableGeneralSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneralSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
