/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2106
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// FarmStorageSettingsInfo Virtual center storage settings for the farm.
type FarmStorageSettingsInfo struct {
	// List of IDs of the datastore used to store the RDS Server.
	Datastores *[]FarmDatastoreSettingsInfo `json:"datastores,omitempty"`
	// Datastore to store replica disks for instant clone machines. This is set when use_separate_datastores_replica_and_os_disks is true.
	ReplicaDiskDatastoreId *string `json:"replica_disk_datastore_id,omitempty"`
	// Indicates whether to use separate datastores for replica and OS disks.
	UseSeparateDatastoresReplicaAndOsDisks *bool `json:"use_separate_datastores_replica_and_os_disks,omitempty"`
	// Indicates whether to use view storage accelerator.
	UseViewStorageAccelerator *bool `json:"use_view_storage_accelerator,omitempty"`
	// Indicates whether to use vSphere VSAN.
	UseVsan *bool `json:"use_vsan,omitempty"`
}

// NewFarmStorageSettingsInfo instantiates a new FarmStorageSettingsInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFarmStorageSettingsInfo() *FarmStorageSettingsInfo {
	this := FarmStorageSettingsInfo{}
	return &this
}

// NewFarmStorageSettingsInfoWithDefaults instantiates a new FarmStorageSettingsInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFarmStorageSettingsInfoWithDefaults() *FarmStorageSettingsInfo {
	this := FarmStorageSettingsInfo{}
	return &this
}

// GetDatastores returns the Datastores field value if set, zero value otherwise.
func (o *FarmStorageSettingsInfo) GetDatastores() []FarmDatastoreSettingsInfo {
	if o == nil || o.Datastores == nil {
		var ret []FarmDatastoreSettingsInfo
		return ret
	}
	return *o.Datastores
}

// GetDatastoresOk returns a tuple with the Datastores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmStorageSettingsInfo) GetDatastoresOk() (*[]FarmDatastoreSettingsInfo, bool) {
	if o == nil || o.Datastores == nil {
		return nil, false
	}
	return o.Datastores, true
}

// HasDatastores returns a boolean if a field has been set.
func (o *FarmStorageSettingsInfo) HasDatastores() bool {
	if o != nil && o.Datastores != nil {
		return true
	}

	return false
}

// SetDatastores gets a reference to the given []FarmDatastoreSettingsInfo and assigns it to the Datastores field.
func (o *FarmStorageSettingsInfo) SetDatastores(v []FarmDatastoreSettingsInfo) {
	o.Datastores = &v
}

// GetReplicaDiskDatastoreId returns the ReplicaDiskDatastoreId field value if set, zero value otherwise.
func (o *FarmStorageSettingsInfo) GetReplicaDiskDatastoreId() string {
	if o == nil || o.ReplicaDiskDatastoreId == nil {
		var ret string
		return ret
	}
	return *o.ReplicaDiskDatastoreId
}

// GetReplicaDiskDatastoreIdOk returns a tuple with the ReplicaDiskDatastoreId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmStorageSettingsInfo) GetReplicaDiskDatastoreIdOk() (*string, bool) {
	if o == nil || o.ReplicaDiskDatastoreId == nil {
		return nil, false
	}
	return o.ReplicaDiskDatastoreId, true
}

// HasReplicaDiskDatastoreId returns a boolean if a field has been set.
func (o *FarmStorageSettingsInfo) HasReplicaDiskDatastoreId() bool {
	if o != nil && o.ReplicaDiskDatastoreId != nil {
		return true
	}

	return false
}

// SetReplicaDiskDatastoreId gets a reference to the given string and assigns it to the ReplicaDiskDatastoreId field.
func (o *FarmStorageSettingsInfo) SetReplicaDiskDatastoreId(v string) {
	o.ReplicaDiskDatastoreId = &v
}

// GetUseSeparateDatastoresReplicaAndOsDisks returns the UseSeparateDatastoresReplicaAndOsDisks field value if set, zero value otherwise.
func (o *FarmStorageSettingsInfo) GetUseSeparateDatastoresReplicaAndOsDisks() bool {
	if o == nil || o.UseSeparateDatastoresReplicaAndOsDisks == nil {
		var ret bool
		return ret
	}
	return *o.UseSeparateDatastoresReplicaAndOsDisks
}

// GetUseSeparateDatastoresReplicaAndOsDisksOk returns a tuple with the UseSeparateDatastoresReplicaAndOsDisks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmStorageSettingsInfo) GetUseSeparateDatastoresReplicaAndOsDisksOk() (*bool, bool) {
	if o == nil || o.UseSeparateDatastoresReplicaAndOsDisks == nil {
		return nil, false
	}
	return o.UseSeparateDatastoresReplicaAndOsDisks, true
}

// HasUseSeparateDatastoresReplicaAndOsDisks returns a boolean if a field has been set.
func (o *FarmStorageSettingsInfo) HasUseSeparateDatastoresReplicaAndOsDisks() bool {
	if o != nil && o.UseSeparateDatastoresReplicaAndOsDisks != nil {
		return true
	}

	return false
}

// SetUseSeparateDatastoresReplicaAndOsDisks gets a reference to the given bool and assigns it to the UseSeparateDatastoresReplicaAndOsDisks field.
func (o *FarmStorageSettingsInfo) SetUseSeparateDatastoresReplicaAndOsDisks(v bool) {
	o.UseSeparateDatastoresReplicaAndOsDisks = &v
}

// GetUseViewStorageAccelerator returns the UseViewStorageAccelerator field value if set, zero value otherwise.
func (o *FarmStorageSettingsInfo) GetUseViewStorageAccelerator() bool {
	if o == nil || o.UseViewStorageAccelerator == nil {
		var ret bool
		return ret
	}
	return *o.UseViewStorageAccelerator
}

// GetUseViewStorageAcceleratorOk returns a tuple with the UseViewStorageAccelerator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmStorageSettingsInfo) GetUseViewStorageAcceleratorOk() (*bool, bool) {
	if o == nil || o.UseViewStorageAccelerator == nil {
		return nil, false
	}
	return o.UseViewStorageAccelerator, true
}

// HasUseViewStorageAccelerator returns a boolean if a field has been set.
func (o *FarmStorageSettingsInfo) HasUseViewStorageAccelerator() bool {
	if o != nil && o.UseViewStorageAccelerator != nil {
		return true
	}

	return false
}

// SetUseViewStorageAccelerator gets a reference to the given bool and assigns it to the UseViewStorageAccelerator field.
func (o *FarmStorageSettingsInfo) SetUseViewStorageAccelerator(v bool) {
	o.UseViewStorageAccelerator = &v
}

// GetUseVsan returns the UseVsan field value if set, zero value otherwise.
func (o *FarmStorageSettingsInfo) GetUseVsan() bool {
	if o == nil || o.UseVsan == nil {
		var ret bool
		return ret
	}
	return *o.UseVsan
}

// GetUseVsanOk returns a tuple with the UseVsan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmStorageSettingsInfo) GetUseVsanOk() (*bool, bool) {
	if o == nil || o.UseVsan == nil {
		return nil, false
	}
	return o.UseVsan, true
}

// HasUseVsan returns a boolean if a field has been set.
func (o *FarmStorageSettingsInfo) HasUseVsan() bool {
	if o != nil && o.UseVsan != nil {
		return true
	}

	return false
}

// SetUseVsan gets a reference to the given bool and assigns it to the UseVsan field.
func (o *FarmStorageSettingsInfo) SetUseVsan(v bool) {
	o.UseVsan = &v
}

func (o FarmStorageSettingsInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Datastores != nil {
		toSerialize["datastores"] = o.Datastores
	}
	if o.ReplicaDiskDatastoreId != nil {
		toSerialize["replica_disk_datastore_id"] = o.ReplicaDiskDatastoreId
	}
	if o.UseSeparateDatastoresReplicaAndOsDisks != nil {
		toSerialize["use_separate_datastores_replica_and_os_disks"] = o.UseSeparateDatastoresReplicaAndOsDisks
	}
	if o.UseViewStorageAccelerator != nil {
		toSerialize["use_view_storage_accelerator"] = o.UseViewStorageAccelerator
	}
	if o.UseVsan != nil {
		toSerialize["use_vsan"] = o.UseVsan
	}
	return json.Marshal(toSerialize)
}

type NullableFarmStorageSettingsInfo struct {
	value *FarmStorageSettingsInfo
	isSet bool
}

func (v NullableFarmStorageSettingsInfo) Get() *FarmStorageSettingsInfo {
	return v.value
}

func (v *NullableFarmStorageSettingsInfo) Set(val *FarmStorageSettingsInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFarmStorageSettingsInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFarmStorageSettingsInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFarmStorageSettingsInfo(val *FarmStorageSettingsInfo) *NullableFarmStorageSettingsInfo {
	return &NullableFarmStorageSettingsInfo{value: val, isSet: true}
}

func (v NullableFarmStorageSettingsInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFarmStorageSettingsInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
