/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2106
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// VMTemplateInfo Information related to VM template.
type VMTemplateInfo struct {
	// Datacenter id for this VM template.
	DatacenterId string `json:"datacenter_id"`
	// Sum of capacities of all the virtual disks in the template, in bytes.
	DiskSizeInBytes int64 `json:"disk_size_in_bytes"`
	// Unique ID representing a VM template.
	Id string `json:"id"`
	// Reasons that may preclude this VM template from being used in full clone desktop pool creation.
	IncompatibleReasons []string `json:"incompatible_reasons"`
	// Memory size of the VM template, in MB
	MemoryMb int32 `json:"memory_mb"`
	// VM template name.
	Name string `json:"name"`
	// Operating system. * UNKNOWN: Unknown * WINDOWS_XP: Windows XP * WINDOWS_VISTA: Windows Vista * WINDOWS_7: Windows 7 * WINDOWS_8: Windows 8 * WINDOWS_10: Windows 10 * WINDOWS_SERVER_2003: Windows Server 2003 * WINDOWS_SERVER_2008: Windows Server 2008 * WINDOWS_SERVER_2008_R2: Windows Server 2008 R2 * WINDOWS_SERVER_2012: Windows Server 2012 * WINDOWS_SERVER_2012_R2: Windows Server 2012 R2 * WINDOWS_SERVER_2016_OR_ABOVE: Windows Server 2016 or above * LINUX_OTHER: Linux (other) * LINUX_SERVER_OTHER: Linux server (other) * LINUX_UBUNTU: Linux (Ubuntu) * LINUX_RHEL: Linux (Red Hat Enterprise) * LINUX_SUSE: Linux (Suse) * LINUX_CENTOS: Linux (CentOS)
	OperatingSystem string `json:"operating_system"`
	// Operating system display name from Virtual Center.
	OperatingSystemDisplayName string `json:"operating_system_display_name"`
	// VM template path.
	Path string `json:"path"`
	// ID of the vCenter to which this VM template belongs to.
	VcenterId string `json:"vcenter_id"`
	// NVIDIA GRID vGPU type configured on this VM template.
	VgpuType *string `json:"vgpu_type,omitempty"`
}

// NewVMTemplateInfo instantiates a new VMTemplateInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMTemplateInfo(datacenterId string, diskSizeInBytes int64, id string, incompatibleReasons []string, memoryMb int32, name string, operatingSystem string, operatingSystemDisplayName string, path string, vcenterId string) *VMTemplateInfo {
	this := VMTemplateInfo{}
	this.DatacenterId = datacenterId
	this.DiskSizeInBytes = diskSizeInBytes
	this.Id = id
	this.IncompatibleReasons = incompatibleReasons
	this.MemoryMb = memoryMb
	this.Name = name
	this.OperatingSystem = operatingSystem
	this.OperatingSystemDisplayName = operatingSystemDisplayName
	this.Path = path
	this.VcenterId = vcenterId
	return &this
}

// NewVMTemplateInfoWithDefaults instantiates a new VMTemplateInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMTemplateInfoWithDefaults() *VMTemplateInfo {
	this := VMTemplateInfo{}
	return &this
}

// GetDatacenterId returns the DatacenterId field value
func (o *VMTemplateInfo) GetDatacenterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatacenterId
}

// GetDatacenterIdOk returns a tuple with the DatacenterId field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetDatacenterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatacenterId, true
}

// SetDatacenterId sets field value
func (o *VMTemplateInfo) SetDatacenterId(v string) {
	o.DatacenterId = v
}

// GetDiskSizeInBytes returns the DiskSizeInBytes field value
func (o *VMTemplateInfo) GetDiskSizeInBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskSizeInBytes
}

// GetDiskSizeInBytesOk returns a tuple with the DiskSizeInBytes field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetDiskSizeInBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskSizeInBytes, true
}

// SetDiskSizeInBytes sets field value
func (o *VMTemplateInfo) SetDiskSizeInBytes(v int64) {
	o.DiskSizeInBytes = v
}

// GetId returns the Id field value
func (o *VMTemplateInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VMTemplateInfo) SetId(v string) {
	o.Id = v
}

// GetIncompatibleReasons returns the IncompatibleReasons field value
func (o *VMTemplateInfo) GetIncompatibleReasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.IncompatibleReasons
}

// GetIncompatibleReasonsOk returns a tuple with the IncompatibleReasons field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetIncompatibleReasonsOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncompatibleReasons, true
}

// SetIncompatibleReasons sets field value
func (o *VMTemplateInfo) SetIncompatibleReasons(v []string) {
	o.IncompatibleReasons = v
}

// GetMemoryMb returns the MemoryMb field value
func (o *VMTemplateInfo) GetMemoryMb() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryMb
}

// GetMemoryMbOk returns a tuple with the MemoryMb field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetMemoryMbOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryMb, true
}

// SetMemoryMb sets field value
func (o *VMTemplateInfo) SetMemoryMb(v int32) {
	o.MemoryMb = v
}

// GetName returns the Name field value
func (o *VMTemplateInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VMTemplateInfo) SetName(v string) {
	o.Name = v
}

// GetOperatingSystem returns the OperatingSystem field value
func (o *VMTemplateInfo) GetOperatingSystem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetOperatingSystemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperatingSystem, true
}

// SetOperatingSystem sets field value
func (o *VMTemplateInfo) SetOperatingSystem(v string) {
	o.OperatingSystem = v
}

// GetOperatingSystemDisplayName returns the OperatingSystemDisplayName field value
func (o *VMTemplateInfo) GetOperatingSystemDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperatingSystemDisplayName
}

// GetOperatingSystemDisplayNameOk returns a tuple with the OperatingSystemDisplayName field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetOperatingSystemDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperatingSystemDisplayName, true
}

// SetOperatingSystemDisplayName sets field value
func (o *VMTemplateInfo) SetOperatingSystemDisplayName(v string) {
	o.OperatingSystemDisplayName = v
}

// GetPath returns the Path field value
func (o *VMTemplateInfo) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *VMTemplateInfo) SetPath(v string) {
	o.Path = v
}

// GetVcenterId returns the VcenterId field value
func (o *VMTemplateInfo) GetVcenterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VcenterId
}

// GetVcenterIdOk returns a tuple with the VcenterId field value
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetVcenterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VcenterId, true
}

// SetVcenterId sets field value
func (o *VMTemplateInfo) SetVcenterId(v string) {
	o.VcenterId = v
}

// GetVgpuType returns the VgpuType field value if set, zero value otherwise.
func (o *VMTemplateInfo) GetVgpuType() string {
	if o == nil || o.VgpuType == nil {
		var ret string
		return ret
	}
	return *o.VgpuType
}

// GetVgpuTypeOk returns a tuple with the VgpuType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMTemplateInfo) GetVgpuTypeOk() (*string, bool) {
	if o == nil || o.VgpuType == nil {
		return nil, false
	}
	return o.VgpuType, true
}

// HasVgpuType returns a boolean if a field has been set.
func (o *VMTemplateInfo) HasVgpuType() bool {
	if o != nil && o.VgpuType != nil {
		return true
	}

	return false
}

// SetVgpuType gets a reference to the given string and assigns it to the VgpuType field.
func (o *VMTemplateInfo) SetVgpuType(v string) {
	o.VgpuType = &v
}

func (o VMTemplateInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["datacenter_id"] = o.DatacenterId
	}
	if true {
		toSerialize["disk_size_in_bytes"] = o.DiskSizeInBytes
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["incompatible_reasons"] = o.IncompatibleReasons
	}
	if true {
		toSerialize["memory_mb"] = o.MemoryMb
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["operating_system"] = o.OperatingSystem
	}
	if true {
		toSerialize["operating_system_display_name"] = o.OperatingSystemDisplayName
	}
	if true {
		toSerialize["path"] = o.Path
	}
	if true {
		toSerialize["vcenter_id"] = o.VcenterId
	}
	if o.VgpuType != nil {
		toSerialize["vgpu_type"] = o.VgpuType
	}
	return json.Marshal(toSerialize)
}

type NullableVMTemplateInfo struct {
	value *VMTemplateInfo
	isSet bool
}

func (v NullableVMTemplateInfo) Get() *VMTemplateInfo {
	return v.value
}

func (v *NullableVMTemplateInfo) Set(val *VMTemplateInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVMTemplateInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVMTemplateInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMTemplateInfo(val *VMTemplateInfo) *NullableVMTemplateInfo {
	return &NullableVMTemplateInfo{value: val, isSet: true}
}

func (v NullableVMTemplateInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMTemplateInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
