/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2106
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// NotFilter struct for NotFilter
type NotFilter struct {
	BaseFilter
	Filter *BaseFilter `json:"filter,omitempty"`
	Type   *string     `json:"type,omitempty"`
}

// NewNotFilter instantiates a new NotFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotFilter() *NotFilter {
	this := NotFilter{}
	return &this
}

// NewNotFilterWithDefaults instantiates a new NotFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotFilterWithDefaults() *NotFilter {
	this := NotFilter{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *NotFilter) GetFilter() BaseFilter {
	if o == nil || o.Filter == nil {
		var ret BaseFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotFilter) GetFilterOk() (*BaseFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *NotFilter) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given BaseFilter and assigns it to the Filter field.
func (o *NotFilter) SetFilter(v BaseFilter) {
	o.Filter = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NotFilter) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotFilter) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NotFilter) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NotFilter) SetType(v string) {
	o.Type = &v
}

func (o NotFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseFilter, errBaseFilter := json.Marshal(o.BaseFilter)
	if errBaseFilter != nil {
		return []byte{}, errBaseFilter
	}
	errBaseFilter = json.Unmarshal([]byte(serializedBaseFilter), &toSerialize)
	if errBaseFilter != nil {
		return []byte{}, errBaseFilter
	}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableNotFilter struct {
	value *NotFilter
	isSet bool
}

func (v NullableNotFilter) Get() *NotFilter {
	return v.value
}

func (v *NullableNotFilter) Set(val *NotFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableNotFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableNotFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotFilter(val *NotFilter) *NullableNotFilter {
	return &NullableNotFilter{value: val, isSet: true}
}

func (v NullableNotFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
