/*
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

// BulkEntitlementResponseInfo Response for each of the entitlement operation for a resource in a bulk entitlement operation.
type BulkEntitlementResponseInfo struct {
	// List of entitlement response info objects correpsonding to each of the given ad-user-or-group SID.
	Details []EntitlementResponseInfo `json:"details,omitempty"`
	// Reasons for the failure of the operation.
	ErrorMessages []string `json:"error_messages,omitempty"`
	// Unique ID representing the resource for the entitlement operation.
	Id string `json:"id,omitempty"`
	// Response HTTP status code of the operation.
	StatusCode int32 `json:"status_code,omitempty"`
	// Timestamp in milliseconds when the operation failed. Measured as epoch time.
	Timestamp int64 `json:"timestamp,omitempty"`
}
