/*
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

// AuthTokens Authentication Tokens
type AuthTokens struct {
	// Access Token to be used in API calls.
	AccessToken string `json:"access_token"`
	// Refresh Token to be used to get a new Access token.
	RefreshToken string `json:"refresh_token"`
}
