/*
 * Horizon Server API
 *
 * Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

// DesktopPoolProvisioningSettings Virtual Center provisioning settings for the automated desktop pool.
type DesktopPoolProvisioningSettings struct {
	// Whether to add Virtual TPM device.
	AddVirtualTpm bool `json:"add_virtual_tpm,omitempty"`
	// Applicable To: Linked/instant clone automated desktop pools.<br>Base image snapshot for linked clone desktop pool and current image snapshot for instant clone desktop pool.
	BaseSnapshotId string `json:"base_snapshot_id,omitempty"`
	// Datacenter within which the desktop pool is configured.
	DatacenterId string `json:"datacenter_id,omitempty"`
	// Host or cluster where the machines are deployed in.
	HostOrClusterId string `json:"host_or_cluster_id,omitempty"`
	// Applicable To: Full/instant clone automated desktop pools.<br>Image management stream used in desktop pool when Image Management feature is enabled.
	ImStreamId string `json:"im_stream_id,omitempty"`
	// Applicable To: Full/instant clone automated desktop pools.<br>Image management tag associated with the selected image management stream which is used in desktop pool when Image Management feature is enabled.
	ImTagId string `json:"im_tag_id,omitempty"`
	// Applicable To: Linked clone automated desktop pools.<br>Minimum number of ready (provisioned) machines during View Composer maintenance operations.
	MinReadyVmsOnVcomposerMaintenance int32 `json:"min_ready_vms_on_vcomposer_maintenance,omitempty"`
	// Applicable To: Linked/instant clone automated desktop pools.<br>Base image VM for linked clone desktop pool and current image for instant clone desktop pool.
	ParentVmId string `json:"parent_vm_id,omitempty"`
	// Resource pool to deploy the machines.
	ResourcePoolId string `json:"resource_pool_id,omitempty"`
	// VM folder where the machines are deployed to.
	VmFolderId string `json:"vm_folder_id,omitempty"`
	// Applicable To: Full clone automated desktop pools.<br>Template from which full clone machines are deployed.
	VmTemplateId string `json:"vm_template_id,omitempty"`
}
