/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2106
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// ConnectionServerMonitorInfoV2 Monitoring information related to Connection Server.
type ConnectionServerMonitorInfoV2 struct {
	Certificate CertificateMonitorInfo `json:"certificate"`
	// Number of connections to this Connection Server.
	ConnectionCount *int32 `json:"connection_count,omitempty"`
	// Connection Server replication status with respect to the Peer Connection Servers in the same cluster.
	CsReplications *[]ConnectionServerMonitorCSReplication `json:"cs_replications,omitempty"`
	// Indicates whether server has the default certificate.
	DefaultCertificate *bool                          `json:"default_certificate,omitempty"`
	Details            ConnectionServerMonitorDetails `json:"details"`
	// Unique ID of the Connection Server.
	Id string `json:"id"`
	// The timestamp in milliseconds when the last update was obtained. Measured as epoch time.
	LastUpdatedTimestamp *int64 `json:"last_updated_timestamp,omitempty"`
	// Connection Server host name or IP address.
	Name string `json:"name"`
	// Connection Server related Windows services information.
	Services *[]ConnectionServerMonitorServiceStatus `json:"services,omitempty"`
	// PCoIP, RDP or BLAST protocol sessions details when clients connect directly to the connection server.
	SessionProtocolData *[]ConnectionServerSessionProtocolData `json:"session_protocol_data,omitempty"`
	// The maximum number of connections allowed for the connection server through the Horizon client. If all of the secure gateways (HTTP(S)/PCOIP/BLAST) are enabled, this field denotes the maximum number of connections allowed for the connection server.If none of the secure gateways(HTTP(S)/PCOIP/BLAST) are enabled, sessionThreshold value will not be set.
	SessionThreshold *int32 `json:"session_threshold,omitempty"`
	// Status of the Connection Server. * OK: The Connection Server is working properly. * ERROR: Error occurred when connecting to Connection Server. * NOT_RESPONDING: The Connection Server is not responding. * UNKNOWN: Status of Connection Server is unknown.
	Status string `json:"status"`
	// Number of connections tunneled through this Connection Server.
	TunnelConnectionCount *int32 `json:"tunnel_connection_count,omitempty"`
}

// NewConnectionServerMonitorInfoV2 instantiates a new ConnectionServerMonitorInfoV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionServerMonitorInfoV2(certificate CertificateMonitorInfo, details ConnectionServerMonitorDetails, id string, name string, status string) *ConnectionServerMonitorInfoV2 {
	this := ConnectionServerMonitorInfoV2{}
	this.Certificate = certificate
	this.Details = details
	this.Id = id
	this.Name = name
	this.Status = status
	return &this
}

// NewConnectionServerMonitorInfoV2WithDefaults instantiates a new ConnectionServerMonitorInfoV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionServerMonitorInfoV2WithDefaults() *ConnectionServerMonitorInfoV2 {
	this := ConnectionServerMonitorInfoV2{}
	return &this
}

// GetCertificate returns the Certificate field value
func (o *ConnectionServerMonitorInfoV2) GetCertificate() CertificateMonitorInfo {
	if o == nil {
		var ret CertificateMonitorInfo
		return ret
	}

	return o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetCertificateOk() (*CertificateMonitorInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Certificate, true
}

// SetCertificate sets field value
func (o *ConnectionServerMonitorInfoV2) SetCertificate(v CertificateMonitorInfo) {
	o.Certificate = v
}

// GetConnectionCount returns the ConnectionCount field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetConnectionCount() int32 {
	if o == nil || o.ConnectionCount == nil {
		var ret int32
		return ret
	}
	return *o.ConnectionCount
}

// GetConnectionCountOk returns a tuple with the ConnectionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetConnectionCountOk() (*int32, bool) {
	if o == nil || o.ConnectionCount == nil {
		return nil, false
	}
	return o.ConnectionCount, true
}

// HasConnectionCount returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasConnectionCount() bool {
	if o != nil && o.ConnectionCount != nil {
		return true
	}

	return false
}

// SetConnectionCount gets a reference to the given int32 and assigns it to the ConnectionCount field.
func (o *ConnectionServerMonitorInfoV2) SetConnectionCount(v int32) {
	o.ConnectionCount = &v
}

// GetCsReplications returns the CsReplications field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetCsReplications() []ConnectionServerMonitorCSReplication {
	if o == nil || o.CsReplications == nil {
		var ret []ConnectionServerMonitorCSReplication
		return ret
	}
	return *o.CsReplications
}

// GetCsReplicationsOk returns a tuple with the CsReplications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetCsReplicationsOk() (*[]ConnectionServerMonitorCSReplication, bool) {
	if o == nil || o.CsReplications == nil {
		return nil, false
	}
	return o.CsReplications, true
}

// HasCsReplications returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasCsReplications() bool {
	if o != nil && o.CsReplications != nil {
		return true
	}

	return false
}

// SetCsReplications gets a reference to the given []ConnectionServerMonitorCSReplication and assigns it to the CsReplications field.
func (o *ConnectionServerMonitorInfoV2) SetCsReplications(v []ConnectionServerMonitorCSReplication) {
	o.CsReplications = &v
}

// GetDefaultCertificate returns the DefaultCertificate field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetDefaultCertificate() bool {
	if o == nil || o.DefaultCertificate == nil {
		var ret bool
		return ret
	}
	return *o.DefaultCertificate
}

// GetDefaultCertificateOk returns a tuple with the DefaultCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetDefaultCertificateOk() (*bool, bool) {
	if o == nil || o.DefaultCertificate == nil {
		return nil, false
	}
	return o.DefaultCertificate, true
}

// HasDefaultCertificate returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasDefaultCertificate() bool {
	if o != nil && o.DefaultCertificate != nil {
		return true
	}

	return false
}

// SetDefaultCertificate gets a reference to the given bool and assigns it to the DefaultCertificate field.
func (o *ConnectionServerMonitorInfoV2) SetDefaultCertificate(v bool) {
	o.DefaultCertificate = &v
}

// GetDetails returns the Details field value
func (o *ConnectionServerMonitorInfoV2) GetDetails() ConnectionServerMonitorDetails {
	if o == nil {
		var ret ConnectionServerMonitorDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetDetailsOk() (*ConnectionServerMonitorDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *ConnectionServerMonitorInfoV2) SetDetails(v ConnectionServerMonitorDetails) {
	o.Details = v
}

// GetId returns the Id field value
func (o *ConnectionServerMonitorInfoV2) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConnectionServerMonitorInfoV2) SetId(v string) {
	o.Id = v
}

// GetLastUpdatedTimestamp returns the LastUpdatedTimestamp field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetLastUpdatedTimestamp() int64 {
	if o == nil || o.LastUpdatedTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.LastUpdatedTimestamp
}

// GetLastUpdatedTimestampOk returns a tuple with the LastUpdatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetLastUpdatedTimestampOk() (*int64, bool) {
	if o == nil || o.LastUpdatedTimestamp == nil {
		return nil, false
	}
	return o.LastUpdatedTimestamp, true
}

// HasLastUpdatedTimestamp returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasLastUpdatedTimestamp() bool {
	if o != nil && o.LastUpdatedTimestamp != nil {
		return true
	}

	return false
}

// SetLastUpdatedTimestamp gets a reference to the given int64 and assigns it to the LastUpdatedTimestamp field.
func (o *ConnectionServerMonitorInfoV2) SetLastUpdatedTimestamp(v int64) {
	o.LastUpdatedTimestamp = &v
}

// GetName returns the Name field value
func (o *ConnectionServerMonitorInfoV2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectionServerMonitorInfoV2) SetName(v string) {
	o.Name = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetServices() []ConnectionServerMonitorServiceStatus {
	if o == nil || o.Services == nil {
		var ret []ConnectionServerMonitorServiceStatus
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetServicesOk() (*[]ConnectionServerMonitorServiceStatus, bool) {
	if o == nil || o.Services == nil {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasServices() bool {
	if o != nil && o.Services != nil {
		return true
	}

	return false
}

// SetServices gets a reference to the given []ConnectionServerMonitorServiceStatus and assigns it to the Services field.
func (o *ConnectionServerMonitorInfoV2) SetServices(v []ConnectionServerMonitorServiceStatus) {
	o.Services = &v
}

// GetSessionProtocolData returns the SessionProtocolData field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetSessionProtocolData() []ConnectionServerSessionProtocolData {
	if o == nil || o.SessionProtocolData == nil {
		var ret []ConnectionServerSessionProtocolData
		return ret
	}
	return *o.SessionProtocolData
}

// GetSessionProtocolDataOk returns a tuple with the SessionProtocolData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetSessionProtocolDataOk() (*[]ConnectionServerSessionProtocolData, bool) {
	if o == nil || o.SessionProtocolData == nil {
		return nil, false
	}
	return o.SessionProtocolData, true
}

// HasSessionProtocolData returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasSessionProtocolData() bool {
	if o != nil && o.SessionProtocolData != nil {
		return true
	}

	return false
}

// SetSessionProtocolData gets a reference to the given []ConnectionServerSessionProtocolData and assigns it to the SessionProtocolData field.
func (o *ConnectionServerMonitorInfoV2) SetSessionProtocolData(v []ConnectionServerSessionProtocolData) {
	o.SessionProtocolData = &v
}

// GetSessionThreshold returns the SessionThreshold field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetSessionThreshold() int32 {
	if o == nil || o.SessionThreshold == nil {
		var ret int32
		return ret
	}
	return *o.SessionThreshold
}

// GetSessionThresholdOk returns a tuple with the SessionThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetSessionThresholdOk() (*int32, bool) {
	if o == nil || o.SessionThreshold == nil {
		return nil, false
	}
	return o.SessionThreshold, true
}

// HasSessionThreshold returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasSessionThreshold() bool {
	if o != nil && o.SessionThreshold != nil {
		return true
	}

	return false
}

// SetSessionThreshold gets a reference to the given int32 and assigns it to the SessionThreshold field.
func (o *ConnectionServerMonitorInfoV2) SetSessionThreshold(v int32) {
	o.SessionThreshold = &v
}

// GetStatus returns the Status field value
func (o *ConnectionServerMonitorInfoV2) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConnectionServerMonitorInfoV2) SetStatus(v string) {
	o.Status = v
}

// GetTunnelConnectionCount returns the TunnelConnectionCount field value if set, zero value otherwise.
func (o *ConnectionServerMonitorInfoV2) GetTunnelConnectionCount() int32 {
	if o == nil || o.TunnelConnectionCount == nil {
		var ret int32
		return ret
	}
	return *o.TunnelConnectionCount
}

// GetTunnelConnectionCountOk returns a tuple with the TunnelConnectionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionServerMonitorInfoV2) GetTunnelConnectionCountOk() (*int32, bool) {
	if o == nil || o.TunnelConnectionCount == nil {
		return nil, false
	}
	return o.TunnelConnectionCount, true
}

// HasTunnelConnectionCount returns a boolean if a field has been set.
func (o *ConnectionServerMonitorInfoV2) HasTunnelConnectionCount() bool {
	if o != nil && o.TunnelConnectionCount != nil {
		return true
	}

	return false
}

// SetTunnelConnectionCount gets a reference to the given int32 and assigns it to the TunnelConnectionCount field.
func (o *ConnectionServerMonitorInfoV2) SetTunnelConnectionCount(v int32) {
	o.TunnelConnectionCount = &v
}

func (o ConnectionServerMonitorInfoV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["certificate"] = o.Certificate
	}
	if o.ConnectionCount != nil {
		toSerialize["connection_count"] = o.ConnectionCount
	}
	if o.CsReplications != nil {
		toSerialize["cs_replications"] = o.CsReplications
	}
	if o.DefaultCertificate != nil {
		toSerialize["default_certificate"] = o.DefaultCertificate
	}
	if true {
		toSerialize["details"] = o.Details
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.LastUpdatedTimestamp != nil {
		toSerialize["last_updated_timestamp"] = o.LastUpdatedTimestamp
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	if o.SessionProtocolData != nil {
		toSerialize["session_protocol_data"] = o.SessionProtocolData
	}
	if o.SessionThreshold != nil {
		toSerialize["session_threshold"] = o.SessionThreshold
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.TunnelConnectionCount != nil {
		toSerialize["tunnel_connection_count"] = o.TunnelConnectionCount
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionServerMonitorInfoV2 struct {
	value *ConnectionServerMonitorInfoV2
	isSet bool
}

func (v NullableConnectionServerMonitorInfoV2) Get() *ConnectionServerMonitorInfoV2 {
	return v.value
}

func (v *NullableConnectionServerMonitorInfoV2) Set(val *ConnectionServerMonitorInfoV2) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionServerMonitorInfoV2) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionServerMonitorInfoV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionServerMonitorInfoV2(val *ConnectionServerMonitorInfoV2) *NullableConnectionServerMonitorInfoV2 {
	return &NullableConnectionServerMonitorInfoV2{value: val, isSet: true}
}

func (v NullableConnectionServerMonitorInfoV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionServerMonitorInfoV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
